# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: LaTeX compilation
      uses: dante-ev/latex-action@latest
      with:
        root_file: ./file.tex
        args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    - name: Renaming File
      run: mv main.pdf CV_AubinMazet_EN.pdf
    - name: Push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'Update PDF'
        force-add: 'true'
        files: CV_AubinMazet_EN.pdf
        name: Aubin Mazet
        email: mazetaubin@gmail.com 